site_name: Amazon Containers Blog Maelstrom
repo_name: "aws-samples/containers-blog-maelstrom"
repo_url: "https://github.com/aws-samples/containers-blog-maelstrom"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Solutions:
    - ALB Ingress Sharing and Target Group Binding: 'ALB-ingresssharing-tbg.md'
    - Managing AMG using Grafana Operator: 'grafana-operator-AMG.md'
    - Batch Processing with K8s: 'batch-processing-with-k8s.md'
    - Unlocking Insights - Turning Application Logs into Actionable Metrics: 'capture-errors-k8s-slack.md'
    - Prefetch Images to EKS nodes: 'prefetch-data-to-eks-nodes.md'
    - Semantic Versioning App Runner: 'semantic-versioning-app-runner.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search
