apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: Package
metadata:
  name: curated-metrics-server
  namespace: eksa-packages-{{EKSA_CLUSTER_NAME}}
spec:
  packageName: metrics-server
  targetNamespace: {{NAMESPACE}}
  config: |-
    args:
      - "--kubelet-insecure-tls"
---
